all:
  children:
    dev:
      hosts:  
         xxx.xxx.xxx.xxx:   # server
    stg:
      hosts:
        xxx.xxx.xxx.xxx:   # server
    prod:
      hosts:
        xxx.xxx.xxx.xxx:   # server

  vars: 
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
