all:
  children:
    dev:
      hosts:  
         xxx.xxx.xxx.xxx:   # server ip
    stg:
      hosts:
        xxx.xxx.xxx.xxx:   # server ip
    prod:
      hosts:
        xxx.xxx.xxx.xxx:   # server ip

  vars: 
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
